[package]
name = "xtask"
version = "4.4.0"
edition = "2024"

[dependencies]
log = "0.4.28"
strum = "0.27.2"

tracel-xtask = "=4.4.0"
# ### For local development. ###
# tracel-xtask = { path = "../../xtask/crates/tracel-xtask", default-features = false }
