[alias]
gen = "run --release --target-dir target/terrars-gen --package terrars-gen --bin terrars-gen --"
xtask = "run --manifest-path ./xtask/Cargo.toml --target-dir target/xtask --package xtask --bin xtask --"